version: '3'

services:
  # app:
  #   container_name: app
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ../:/app
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - ../.env
  #   networks:
  #     - axum-sqlx-example

  db:
    hostname: db
    image: postgres:15.2
    restart: unless-stopped
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    env_file:
      # Ensure that the variables in .env match the same variables in devcontainer.json
      - ../.env
    networks:
      - axum-sqlx-example

networks:
  axum-sqlx-example:
    external: true
